# Generated by Django 5.2.5 on 2026-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default.jpg', null=True, upload_to='user_avatars'),
        ),
    ]
